// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CtecMateriais.Migrations
{
    [DbContext(typeof(MateriaisContext))]
    [Migration("20210522180515_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ctec_Materiais.Models.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasMaxLength(3);

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("IdMaterial");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Ctec_Materiais.Models.RegistroRetirada", b =>
                {
                    b.Property<int>("IdRetirada")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Retirada");

                    b.Property<int>("Status");

                    b.Property<int>("TotalRetiradas");

                    b.Property<int?>("UsuarioIdUsuario");

                    b.HasKey("IdRetirada");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("RegistroRetirada");
                });

            modelBuilder.Entity("Ctec_Materiais.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<int?>("MaterialIdMaterial");

                    b.Property<string>("Nome");

                    b.HasKey("IdUsuario");

                    b.HasIndex("MaterialIdMaterial");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Ctec_Materiais.Models.RegistroRetirada", b =>
                {
                    b.HasOne("Ctec_Materiais.Models.Usuario", "Usuario")
                        .WithMany("Retiradas")
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("Ctec_Materiais.Models.Usuario", b =>
                {
                    b.HasOne("Ctec_Materiais.Models.Material", "Material")
                        .WithMany("Usuarios")
                        .HasForeignKey("MaterialIdMaterial");
                });
#pragma warning restore 612, 618
        }
    }
}
